### ISSUE TITLE
Objects not showing correctly

### ISSUE THREAD

**Issue by manicolan** [kpiorno/kivy3dgui#14]
Any idea why this happens for some objects?
Kivy vesion: 2.0.0rc4
[Objects here](https://github.com/kpiorno/kivy3dgui/files/5645823/untitled.zip)

```
from kivy.app import App
from kivy.lang import Builder

class ExampleApp(App):

    def build(self):
        root = Builder.load_string('''

#: import Layout3D kivy3dgui.layout3d
Layout3D:
    id: par
    size_hint: (1.0, 1.0)
    Node:
        id: Node1
        name: 'Node 0'
        rotate: (270, 90, 0, 0)
        # scale: (0.2, 0.2, 0.2)
        translate: (0, -10, -50)
        meshes: ("./untitled.obj", )
        FloatLayout:
            canvas:
                Color:
                    rgb: 1, 1, 1, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
        ''')
        self.root = root
        return root


if __name__ == '__main__':
    ExampleApp().run()

```

![Untitled](https://user-images.githubusercontent.com/75505994/101221159-5db6ef00-369c-11eb-8bdf-2487cd6670ed.png)

**Comment by kpiorno** [comment]
Hi, @manicolan did you test it in a previous Kivy version?

**Comment by kpiorno** [comment]
Ok, I found the issue. The obj file has to be exported with triangulated faces. I opened it with Blender and I exported it with that option.  
[Converted object](https://github.com/kpiorno/kivy3dgui/files/5663051/untitled.zip)
<img width="791" alt="Captura de Pantalla 2020-12-08 a la(s) 18 56 57" src="https://user-images.githubusercontent.com/5463471/101563844-44a58b00-3987-11eb-9365-d56ad4f8caf2.png">

**Comment by manicolan** [comment]
@kpiorno Yeah that works! I think it would be better if you mention this somewhere in the readme file. Thanks a lot!
