### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_node'

### ISSUE THREAD

**Issue by Mamartinezh** [kpiorno/kivy3dgui#16]
I just discovered this repository, when I tried to executed this error pops up

AttributeError: 'NoneType' object has no attribute 'add_node'

![image](https://user-images.githubusercontent.com/64501300/113482364-1848d980-9464-11eb-96b6-50f7368a6c6e.png)

I'm working with the 3d_editor branch.

Any hint of what could be?

Thank you and regards!

**Comment by kpiorno** [comment]
@MateoeslaLey It seems the issue is fixed already.
